<?php get_header(); ?>
<!--==============================================================
About
============================================================== -->
<div class="wrapper">
    <section class="Works">
            <div class="section__title fadein">
                <h2>Works</h2>
                <p>制作実績</p>
            </div>

            <ul>
        <li>
            <a href="#">
                <img src="../images/Top__img/Works_Kindergarden.png" alt="幼稚園サイト画像">
                <p>幼稚園サイト作成</p>
            </a>
            </li>
        <li>
            <a href="#">
                <img src="../images/Top__img/Works__Sneakers.png" alt="スニーカー専門店の画像">
                <p>スニーカー専門店のサイト作成</p>
            </a>
        </li>
        <li>
            <a href="#">
                <img src="../images/Top__img/Works__ProfileSite.png" alt="プロフィールサイト画像">
                <p>プロフィールサイト作成</p>
            </a>
        </li>
        <li>
            <a href="#">
                <img src="../images/Top__img/Works__Dogrun.png" alt="ドッグランサイト画像">
                <p>ドッグランのサイト作成</p>
            </a>
        </li>
        <li>
            <a href="#">
                <img src="../images/Top__img/Works__Officedesign.png" alt="オフィスデザイン会社の画像">
                <p>オフィスデザイン会社のサイト作成</p>
            </a>
        </li>
        <li>
            <a href="#">
                <img src="../images/Top__img/Works__CoffieSite.png" alt="カフェのサイト画像">
                <p>カフェのサイト作成</p>
            </a>
        </li>
        <li>
            <a href="#">
                <img src="../images/Top__img/Works__Travel.png" alt="トラベルブログ画像">
                <p>ブログサイト作成</p>
            </a>
        </li>
        <li>
            <a href="#">
                <img src="../images/Top__img/Works__Aonokensetsu.png" alt="蒼乃建設画像">
                <p>建設会社のサイト作成</p>
            </a>
        </li>
        <li>
            <a href="#">
                <img src="../images/Top__img/Works__Englishschool.png" alt="英会話スクール画像">
                <p>英会話スクールのサイト作成</p>
            </a>
        </li>
        <li>
            <a href="#">
                <img src="../images/Top__img/Works__Myportfolio.png" alt="ポートフォリオサイト画像">
                <p>ポートフォリオサイト作成</p>
            </a>
        </li>
    </ul>
        
</div>
<!--==============================================================
contact
============================================================== -->
<div class="Contact">
    <div class="section__title fadein">
        <h2>Contact</h2>
        <p>お問い合わせ</p>
    </div>

    <p>お仕事のご依頼やご相談はこちら<br>
        お気軽にご連絡ください！
    </p>
<div class="wrapper">
    <div class="button__more ">
        <a href="#">お問い合わせ</a>
    </div>
</div>
</div>

<?php get_footer(); ?>